services:
  - type: web
    name: ed-tech
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APT_INSTALL_PACKAGES
        value: libreoffice imagemagick poppler-utils
